# Generated by Django 3.2.8 on 2021-11-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workshop', '0003_workshopposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('car_license_plat', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('cancelled', 'cancelled'), ('done', 'done')], default='accepted', max_length=30, verbose_name='Reservation status')),
                ('car_type', models.CharField(choices=[('sedan', 'sedan'), ('coupe', 'coupe'), ('wagon', 'wagon'), ('hatchback', 'hatchback'), ('suv', 'suv'), ('van', 'van')], max_length=30, verbose_name='Car type')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.workshopcustomer')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.workshop')),
                ('workshop_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.workshopposition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('workshop', 'date', 'workshop_position'), name='unique_reservations'),
        ),
    ]
