# Generated by Django 3.2.8 on 2021-12-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='car_license_plat',
            new_name='car_license_plate',
        ),
    ]
