# Generated by Django 3.2.8 on 2021-11-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
