# Generated by Django 3.2.8 on 2021-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_workshopposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
